package com.db.dbfrontrunner.admin;


import com.db.dbfrontrunner.response.Response;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Optional;


/*
either you can use
 */

@RestController    // This means that this class is a Controller
@RequestMapping(path="/users") // This means URL's start with /demo (after Application path)
public class AdminController {

	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private AdminRepository adminRepository;


	@PostMapping("/login")
	public Response login(@RequestBody Admin user){

		Optional<Admin>u=adminRepository.findById(user.getId());

		if(u.isPresent()){
			if(u.get().getPassword().equals(user.getPassword()))
		        return new Response(1,"Logged In.","You have successfully Signed In",u);
			else
				return new Response(2,"Wrong Password","Please re-enter password",null);
		}
		else
			return new Response(0,"Admin Not Found","Please enter again",null);
	}
}